### ISSUE TITLE
i think it doesn't need debendances but it give me that 

### ISSUE THREAD

**Issue by zeyad-elkholy** [mohamedamara1/classroom-files-downloader#11]
`./ClassroomFilesDownloader.py: 1: from: not found
./ClassroomFilesDownloader.py: 4: from: not found
./ClassroomFilesDownloader.py: 5: from: not found
./ClassroomFilesDownloader.py: 6: from: not found
./ClassroomFilesDownloader.py: 7: from: not found
./ClassroomFilesDownloader.py: 8: from: not found
./ClassroomFilesDownloader.py: 9: from: not found
./ClassroomFilesDownloader.py: 14: from: not found
./ClassroomFilesDownloader.py: 17: Syntax error: "(" unexpected
`

**Comment by zeyad-elkholy** [comment]
`Traceback (most recent call last):
  File "/home/zod/src/ClassroomFilesDownloader.py", line 225, in <module>
    main()
  File "/home/zod/src/ClassroomFilesDownloader.py", line 19, in main
    service = get_classroom_service()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zod/src/ClassroomFilesDownloader.py", line 70, in get_classroom_service
    flow = InstalledAppFlow.from_client_secrets_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zod/src/pyenv/lib/python3.12/site-packages/google_auth_oauthlib/flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'
`
the file is behind it btw i didn't know why it doesn't recognize it i make the name same as the tutorial
